name: my workflow
on: push
permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check container
        uses: docker://alexanderbrevig/kicad-lib-docs:latest
        with:
          args: /kicad-lib-docs symbols "My title" lib.kicad_sym lib.md
      - name: Commit md
        if: github.event_name == 'push'
        run: |
          git config --global user.name "kicad-lib-docs"
          git config --global user.email "kicad-lib-docs@users.noreply.github.com"
          git add lib.md
          git commit -m "docs: kicad-lib-docs"
          git push